---
- job:
    name: dci-ui-test
    parent: base
    description: Run unit tests
    files:
      - src/.*
      - public/.*
      - package.json
      - package-lock.json
      - .zuul.yaml
      - zuul-playbooks/.*
    vars:
      node_version: 10
    run: zuul-playbooks/test.yaml

- project:
    name: dci-ui
    check:
      jobs:
        - dci-ui-test
        - dci-ui-demo:
            voting: false
        - dci-rpm-build
    gate:
      queue: dci
      jobs:
        - dci-ui-test
        - dci-rpm-build
        - dci-rpm-publish
    post:
      queue: dci
      jobs:
        - dci-deploy
