import type { INode } from "analytics/hardware/hardwareFormatter";
import { getHardwareDifferences } from "./hardwareDifference";

describe("getHardwareDifferences", () => {
  test("should be empty with consistent directors", () => {
    const nodes: INode[] = [
      {
        name: "director1",
        role: "director",
        nodeIndex: 1,
        kernel: {
          version: "5.4.0",
          params: { key1: "value1" },
        },
        hardware: {
          node: "director1",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "director1.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          network_interfaces: [
            {
              autonegotiation: true,
              businfo: "pci@0000:00:1f.6",
              description: "Ethernet interface",
              device_id: "0x1234",
              driver: "e1000",
              driver_version: "1.0",
              duplex: "full",
              firmware: "1.0",
              firmware_version: "1.0",
              is_virtual_function: false,
              link_status: true,
              logical_name: "eth0",
              model: "Card1",
              speed_mbps: 1000,
              subdevice_id: null,
              subproduct: null,
              subvendor: null,
              subvendor_id: null,
              vendor: "Vendor1",
              vendor_id: "0x8086",
            },
          ],
          storage_devices: [
            {
              businfo: "scsi@0:0.0.0",
              description: "ATA Disk",
              device_id: "0x5678",
              firmware: "1.0",
              model: "Disk1",
              size_gb: 100,
              type: "disk",
              vendor: "Vendor1",
              vendor_id: "0x1234",
              version: "1.0",
            },
          ],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
      {
        name: "director2",
        role: "director",
        nodeIndex: 2,
        kernel: {
          version: "5.4.0",
          params: { key1: "value1" },
        },
        hardware: {
          node: "director2",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "director2.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          network_interfaces: [
            {
              autonegotiation: true,
              businfo: "pci@0000:00:1f.6",
              description: "Ethernet interface",
              device_id: "0x1234",
              driver: "e1000",
              driver_version: "1.0",
              duplex: "full",
              firmware: "1.0",
              firmware_version: "1.0",
              is_virtual_function: false,
              link_status: true,
              logical_name: "eth0",
              model: "Card1",
              speed_mbps: 1000,
              subdevice_id: null,
              subproduct: null,
              subvendor: null,
              subvendor_id: null,
              vendor: "Vendor1",
              vendor_id: "0x8086",
            },
          ],
          storage_devices: [
            {
              businfo: "scsi@0:0.0.0",
              description: "ATA Disk",
              device_id: "0x5678",
              firmware: "1.0",
              model: "Disk1",
              size_gb: 100,
              type: "disk",
              vendor: "Vendor1",
              vendor_id: "0x1234",
              version: "1.0",
            },
          ],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
    ];

    expect(getHardwareDifferences(nodes)).toEqual([]);
  });
  test("should be empty with one node", () => {
    const nodes: INode[] = [
      {
        name: "director1",
        role: "director",
        nodeIndex: 1,
        kernel: {
          version: "5.4.0",
          params: { key1: "value1" },
        },
        hardware: {
          node: "director1",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "director1.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          network_interfaces: [
            {
              autonegotiation: true,
              businfo: "pci@0000:00:1f.6",
              description: "Ethernet interface",
              device_id: "0x1234",
              driver: "e1000",
              driver_version: "1.0",
              duplex: "full",
              firmware: "1.0",
              firmware_version: "1.0",
              is_virtual_function: false,
              link_status: true,
              logical_name: "eth0",
              model: "Card1",
              speed_mbps: 1000,
              subdevice_id: null,
              subproduct: null,
              subvendor: null,
              subvendor_id: null,
              vendor: "Vendor1",
              vendor_id: "0x8086",
            },
          ],
          storage_devices: [
            {
              businfo: "scsi@0:0.0.0",
              description: "ATA Disk",
              device_id: "0x5678",
              firmware: "1.0",
              model: "Disk1",
              size_gb: 100,
              type: "disk",
              vendor: "Vendor1",
              vendor_id: "0x1234",
              version: "1.0",
            },
          ],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
    ];

    expect(getHardwareDifferences(nodes)).toEqual([]);
  });
  test("should return differences for inconsistent directors", () => {
    const nodes: INode[] = [
      {
        name: "director1",
        role: "director",
        nodeIndex: 1,
        kernel: {
          version: "5.4.0",
          params: { key1: "value1" },
        },
        hardware: {
          node: "director1",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "director1.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          network_interfaces: [],
          storage_devices: [],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
      {
        name: "director2",
        role: "director",
        nodeIndex: 2,
        kernel: {
          version: "5.5.0",
          params: { key1: "value1" },
        },
        hardware: {
          node: "director2",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "director2.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          network_interfaces: [],
          storage_devices: [],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
    ];

    expect(getHardwareDifferences(nodes)).toEqual([
      "Kernel versions differ: 5.4.0, 5.5.0",
    ]);
  });
  test("should return differences for network cards", () => {
    const nodes: INode[] = [
      {
        name: "node1",
        role: "director",
        nodeIndex: 1,
        kernel: null,
        hardware: {
          node: "node1",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node1.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          storage_devices: [],
          network_interfaces: [
            {
              autonegotiation: true,
              businfo: "pci@0000:00:1f.6",
              description: "Ethernet interface",
              device_id: "0x1234",
              driver: "e1000",
              driver_version: "1.0",
              duplex: "full",
              firmware: "1.0",
              firmware_version: "1.0",
              is_virtual_function: false,
              link_status: true,
              logical_name: "eth0",
              model: "Card1",
              speed_mbps: 1000,
              subdevice_id: null,
              subproduct: null,
              subvendor: null,
              subvendor_id: null,
              vendor: "Vendor1",
              vendor_id: "0x8086",
            },
            {
              autonegotiation: true,
              businfo: "pci@0000:01:00.0",
              description: "Ethernet interface",
              device_id: "0x5678",
              driver: "e1000",
              driver_version: "1.0",
              duplex: "full",
              firmware: "1.0",
              firmware_version: "1.0",
              is_virtual_function: false,
              link_status: true,
              logical_name: "eth1",
              model: "Card2",
              speed_mbps: 1000,
              subdevice_id: null,
              subproduct: null,
              subvendor: null,
              subvendor_id: null,
              vendor: "Vendor2",
              vendor_id: "0x8087",
            },
          ],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
      {
        name: "node2",
        role: "director",
        nodeIndex: 2,
        kernel: null,
        hardware: {
          node: "node2",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node2.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          storage_devices: [],
          network_interfaces: [
            {
              autonegotiation: true,
              businfo: "pci@0000:00:1f.6",
              description: "Ethernet interface",
              device_id: "0x1234",
              driver: "e1000",
              driver_version: "1.0",
              duplex: "full",
              firmware: "1.0",
              firmware_version: "1.0",
              is_virtual_function: false,
              link_status: true,
              logical_name: "eth0",
              model: "Card1",
              speed_mbps: 1000,
              subdevice_id: null,
              subproduct: null,
              subvendor: null,
              subvendor_id: null,
              vendor: "Vendor1",
              vendor_id: "0x8086",
            },
            {
              autonegotiation: true,
              businfo: "pci@0000:01:00.0",
              description: "Ethernet interface",
              device_id: "0x5678",
              driver: "e1000",
              driver_version: "1.0",
              duplex: "full",
              firmware: "1.0",
              firmware_version: "1.0",
              is_virtual_function: false,
              link_status: false,
              logical_name: "eth1",
              model: "Card2",
              speed_mbps: 1000,
              subdevice_id: null,
              subproduct: null,
              subvendor: null,
              subvendor_id: null,
              vendor: "Vendor2",
              vendor_id: "0x8087",
            },
          ],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
    ];

    expect(getHardwareDifferences(nodes)).toEqual([
      'Network interface "eth1" differs in: link status (up, down)',
    ]);
  });
  test("should return differences for different network cards numbers", () => {
    const nodes: INode[] = [
      {
        name: "node1",
        role: "director",
        nodeIndex: 1,
        kernel: null,
        hardware: {
          node: "node1",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node1.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          storage_devices: [],
          network_interfaces: [
            {
              autonegotiation: true,
              businfo: "pci@0000:00:1f.6",
              description: "Ethernet interface",
              device_id: "0x1234",
              driver: "e1000",
              driver_version: "1.0",
              duplex: "full",
              firmware: "1.0",
              firmware_version: "1.0",
              is_virtual_function: false,
              link_status: true,
              logical_name: "eth0",
              model: "Card1",
              speed_mbps: 1000,
              subdevice_id: null,
              subproduct: null,
              subvendor: null,
              subvendor_id: null,
              vendor: "Vendor1",
              vendor_id: "0x8086",
            },
          ],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
      {
        name: "node2",
        role: "director",
        nodeIndex: 2,
        kernel: null,
        hardware: {
          node: "node2",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node2.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          storage_devices: [],
          network_interfaces: [
            {
              autonegotiation: true,
              businfo: "pci@0000:00:1f.6",
              description: "Ethernet interface",
              device_id: "0x1234",
              driver: "e1000",
              driver_version: "1.0",
              duplex: "full",
              firmware: "1.0",
              firmware_version: "1.0",
              is_virtual_function: false,
              link_status: true,
              logical_name: "eth0",
              model: "Card1",
              speed_mbps: 1000,
              subdevice_id: null,
              subproduct: null,
              subvendor: null,
              subvendor_id: null,
              vendor: "Vendor1",
              vendor_id: "0x8086",
            },
            {
              autonegotiation: true,
              businfo: "pci@0000:01:00.0",
              description: "Ethernet interface",
              device_id: "0x5678",
              driver: "e1000",
              driver_version: "1.0",
              duplex: "full",
              firmware: "1.0",
              firmware_version: "1.0",
              is_virtual_function: false,
              link_status: true,
              logical_name: "eth1",
              model: "Card2",
              speed_mbps: 1000,
              subdevice_id: null,
              subproduct: null,
              subvendor: null,
              subvendor_id: null,
              vendor: "Vendor1",
              vendor_id: "0x8086",
            },
          ],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
    ];

    expect(getHardwareDifferences(nodes)).toEqual([
      "Number of network cards differs: 1, 2 cards",
    ]);
  });
  test("should return differences for different devices names", () => {
    const nodes: INode[] = [
      {
        name: "node1",
        role: "director",
        nodeIndex: 1,
        kernel: null,
        hardware: {
          node: "node1",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node1.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          network_interfaces: [],
          storage_devices: [
            {
              businfo: "scsi@0:0.0.0",
              description: "ATA Disk",
              device_id: "0x5678",
              firmware: "1.0",
              model: "Disk1",
              size_gb: 100,
              type: "disk",
              vendor: "Vendor1",
              vendor_id: "0x1234",
              version: "1.0",
            },
          ],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
      {
        name: "node2",
        role: "director",
        nodeIndex: 2,
        kernel: null,
        hardware: {
          node: "node2",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node2.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          network_interfaces: [],
          storage_devices: [
            {
              businfo: "scsi@0:0.0.0",
              description: "ATA Disk",
              device_id: "0x5678",
              firmware: "1.0",
              model: "Disk2",
              size_gb: 100,
              type: "disk",
              vendor: "Vendor1",
              vendor_id: "0x1234",
              version: "1.0",
            },
          ],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
    ];

    expect(getHardwareDifferences(nodes)).toEqual([
      'Disk device "/dev/sda" differs in: product (Disk1, Disk2)',
    ]);
  });
  test("should return differences for different memory sticks", () => {
    const nodes: INode[] = [
      {
        name: "node1",
        role: "director",
        nodeIndex: 1,
        kernel: null,
        hardware: {
          node: "node1",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node1.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          storage_devices: [],
          network_interfaces: [],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
      {
        name: "node2",
        role: "director",
        nodeIndex: 2,
        kernel: null,
        hardware: {
          node: "node2",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node2.json",
          memory_dimm_count: 4,
          memory_total_gb: 16,
          storage_devices: [],
          network_interfaces: [],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
    ];

    expect(getHardwareDifferences(nodes)).toEqual([
      "Memory differs: 8 GB, 16 GB",
    ]);
  });
  test("should return differences for different memory sticks", () => {
    const nodes: INode[] = [
      {
        name: "node1",
        role: "director",
        nodeIndex: 1,
        kernel: null,
        hardware: {
          node: "node1",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node1.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          storage_devices: [],
          network_interfaces: [],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
      {
        name: "node2",
        role: "director",
        nodeIndex: 2,
        kernel: null,
        hardware: {
          node: "node2",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node2.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          storage_devices: [],
          network_interfaces: [],
          system_family: "Server",
          system_model: "Product2",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
    ];

    expect(getHardwareDifferences(nodes)).toEqual([
      "Product differs: Product1, Product2",
    ]);
  });
  test("should return differences for different kernel versions", () => {
    const nodes: INode[] = [
      {
        name: "node1",
        role: "director",
        nodeIndex: 1,
        kernel: {
          version: "5.4.0",
          params: { key1: "value1" },
        },
        hardware: {
          node: "node1",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node1.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          storage_devices: [],
          network_interfaces: [],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
      {
        name: "node2",
        role: "director",
        nodeIndex: 2,
        kernel: {
          version: "5.4.1",
          params: { key1: "value1" },
        },
        hardware: {
          node: "node2",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node2.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          storage_devices: [],
          network_interfaces: [],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
    ];

    expect(getHardwareDifferences(nodes)).toEqual([
      "Kernel versions differ: 5.4.0, 5.4.1",
    ]);
  });
  test("should return differences for different kernel params", () => {
    const nodes: INode[] = [
      {
        name: "node1",
        role: "director",
        nodeIndex: 1,
        kernel: {
          version: "5.4.0",
          params: { key1: "value1", key2: "value2" },
        },
        hardware: {
          node: "node1",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node1.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          storage_devices: [],
          network_interfaces: [],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
      {
        name: "node2",
        role: "director",
        nodeIndex: 2,
        kernel: {
          version: "5.4.0",
          params: { key1: "value1" },
        },
        hardware: {
          node: "node2",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node2.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          storage_devices: [],
          network_interfaces: [],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
    ];

    expect(getHardwareDifferences(nodes)).toEqual([
      'Kernel parameter "key2" is missing in some nodes',
    ]);
  });
  test("should ignore UUID for kernels params", () => {
    const nodes: INode[] = [
      {
        name: "node1",
        role: "director",
        nodeIndex: 1,
        kernel: {
          version: "5.4.0",
          params: { key1: "value1", uuid: "UUID=12345" },
        },
        hardware: {
          node: "node1",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node1.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          storage_devices: [],
          network_interfaces: [],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
      {
        name: "node2",
        role: "director",
        nodeIndex: 2,
        kernel: {
          version: "5.4.0",
          params: { key1: "value1", uuid: "UUID=67890" },
        },
        hardware: {
          node: "node2",
          bios_date: "2020-01-01",
          bios_type: "UEFI",
          bios_vendor: "Vendor1",
          bios_version: "BIOS1",
          cpu_frequency_mhz: 2000,
          cpu_model: "CPU1",
          cpu_sockets: 1,
          cpu_total_cores: 4,
          cpu_total_threads: 8,
          cpu_vendor: "Vendor1",
          filename: "node2.json",
          memory_dimm_count: 2,
          memory_total_gb: 8,
          storage_devices: [],
          network_interfaces: [],
          system_family: "Server",
          system_model: "Product1",
          system_sku: "SKU1",
          system_vendor: "Vendor1",
        },
      },
    ];

    expect(getHardwareDifferences(nodes)).toEqual([]);
  });
});
