import {
  PageSection,
  Content,
  Nav,
  NavGroup,
  NavList,
  NavItem,
  ContentVariants,
} from "@patternfly/react-core";
import NotAuthenticatedPage from "./NotAuthenticatedPage";

function RetentionPolicySidebar() {
  return (
    <Nav aria-label="Retention Policy Navigation">
      <NavGroup title="Table of content">
        <NavList>
          <NavItem>
            <a href="#purpose">Purpose</a>
          </NavItem>
          <NavItem>
            <a href="#scope">Scope</a>
          </NavItem>
          <NavItem>
            <a href="#definitions-of-job-data">Definitions of Job Data</a>
          </NavItem>
          <NavItem>
            <a href="#data-storage-locations">Data Storage Locations</a>
          </NavItem>
          <NavItem>
            <a href="#data-access-and-retrieval">Data Access and Retrieval</a>
          </NavItem>
          <NavItem>
            <a href="#retention-period">Retention Period</a>
          </NavItem>
        </NavList>
      </NavGroup>
    </Nav>
  );
}

export default function RetentionPolicyPage() {
  return (
    <NotAuthenticatedPage sidebar={<RetentionPolicySidebar />}>
      <PageSection>
        <Content component={ContentVariants.h1}>
          DCI Data Retention Policy
        </Content>

        <Content component={ContentVariants.h2} id="purpose">
          Purpose
        </Content>
        <Content component={ContentVariants.p}>
          Distributed CI (DCI) is committed to retaining only the data necessary
          to effectively operate its services and fulfill its mission. Data
          retention requirements vary depending on the nature of the data
          collected and the purpose for which it is used. This policy defines
          how job-related data is categorized, stored, accessed, and retained by
          DCI.
        </Content>

        <Content component={ContentVariants.h2} id="scope">
          Scope
        </Content>
        <Content component={ContentVariants.p}>
          This policy applies exclusively to job-related data generated or
          uploaded by partners when using DCI services. It covers data
          associated with job metadata, tasks, and files. It does not apply to
          any other data outside of job execution and reporting.
        </Content>

        <Content component={ContentVariants.h2} id="definitions-of-job-data">
          Definitions of Job Data
        </Content>
        <Content component={ContentVariants.p}>
          For clarity, DCI job data is classified into the following categories:
        </Content>

        <Content component={ContentVariants.h3} id="job-metadata">
          Job Metadata
        </Content>
        <Content component={ContentVariants.p}>
          Job metadata describes the lifecycle and configuration of a job,
          including but not limited to:
        </Content>
        <Content component={ContentVariants.ul}>
          <Content component={ContentVariants.li}>
            Job id, name, status, duration, tags, creation date, etc
          </Content>
          <Content component={ContentVariants.li}>
            Associated pipeline, product, topic, components, test results
          </Content>
        </Content>
        <Content component={ContentVariants.p}>
          This data is used to track, analyze, and report on job execution.
        </Content>

        <Content component={ContentVariants.h3} id="job-tasks">
          Job Tasks
        </Content>
        <Content component={ContentVariants.p}>
          Job tasks correspond to the Ansible tasks executed as part of a job.
          For each task, DCI collects:
        </Content>
        <Content component={ContentVariants.ul}>
          <Content component={ContentVariants.li}>Task name</Content>
          <Content component={ContentVariants.li}>
            Execution result (success, failure, etc.)
          </Content>
          <Content component={ContentVariants.li}>
            Standard output (stdout) and standard error (stderr) generated
            during execution
          </Content>
        </Content>
        <Content component={ContentVariants.p}>
          Task outputs are generated by the DCI agents during job execution.
        </Content>

        <Content component={ContentVariants.h3} id="job-files">
          Job Files
        </Content>
        <Content component={ContentVariants.p}>
          Job files include artifacts that are either:
        </Content>
        <Content component={ContentVariants.ul}>
          <Content component={ContentVariants.li}>
            Uploaded by partners, or
          </Content>
          <Content component={ContentVariants.li}>
            Generated automatically during or after job execution
          </Content>
        </Content>
        <Content component={ContentVariants.p}>
          These files include, but are not limited to:
        </Content>
        <Content component={ContentVariants.ul}>
          <Content component={ContentVariants.li}>Logs</Content>
          <Content component={ContentVariants.li}>JUnit reports</Content>
          <Content component={ContentVariants.li}>
            Other execution artifacts
          </Content>
        </Content>
        <Content component={ContentVariants.p}>
          When JUnit files are uploaded, DCI parses them and stores the
          resulting test data for reporting purposes.
        </Content>

        <Content component={ContentVariants.h2} id="data-storage-locations">
          Data Storage Locations
        </Content>
        <Content component={ContentVariants.p}>
          DCI stores job-related data across multiple storage systems, depending
          on the data type:
        </Content>

        <Content component={ContentVariants.h3} id="dci-database">
          DCI Database
        </Content>
        <Content component={ContentVariants.p}>
          The DCI database stores:
        </Content>
        <Content component={ContentVariants.ul}>
          <Content component={ContentVariants.li}>Job metadata</Content>
          <Content component={ContentVariants.li}>
            Job tasks and files names
          </Content>
          <Content component={ContentVariants.li}>
            Parsed test results derived from JUnit files
          </Content>
        </Content>

        <Content component={ContentVariants.h3} id="amazon-s3">
          Amazon S3
        </Content>
        <Content component={ContentVariants.p}>
          Amazon S3 is used to store:
        </Content>
        <Content component={ContentVariants.ul}>
          <Content component={ContentVariants.li}>
            Job files uploaded by partners
          </Content>
          <Content component={ContentVariants.li}>
            Files generated during job execution (logs, artifacts)
          </Content>
          <Content component={ContentVariants.li}>
            Task outputs, including stdout and stderr
          </Content>
        </Content>

        <Content component={ContentVariants.h3} id="elasticsearch">
          Elasticsearch
        </Content>
        <Content component={ContentVariants.p}>
          Elasticsearch is used for analytics and indexing purposes and
          contains:
        </Content>
        <Content component={ContentVariants.ul}>
          <Content component={ContentVariants.li}>
            Job metadata loaded from the DCI database
          </Content>
          <Content component={ContentVariants.li}>
            Selected data extracted from job to support search, reporting, and
            analytics
          </Content>
        </Content>

        <Content component={ContentVariants.h2} id="data-access-and-retrieval">
          Data Access and Retrieval
        </Content>
        <Content component={ContentVariants.p}>
          Partners may access and retrieve job-related data, including logs and
          artifacts, at any time through the DCI user interface for the duration
          of the retention period.
        </Content>
        <Content component={ContentVariants.p}>
          In addition, job data can be programmatically downloaded using the DCI
          API during the same retention period. Once the retention period has
          expired and data is deleted, it is no longer accessible through either
          the DCI UI or the API.
        </Content>

        <Content component={ContentVariants.h2} id="retention-period">
          Retention Period
        </Content>
        <Content component={ContentVariants.p}>
          DCI retains job-related data according to the following rules:
        </Content>
        <Content component={ContentVariants.ul}>
          <Content component={ContentVariants.li}>
            <strong>
              Retained indefinitely (no deletion as part of this policy):
            </strong>
            <br />
            <strong>Job metadata</strong> (e.g., job ids, creation date, status,
            duration, configuration, components, tags, topic) is kept in the DCI
            database.
          </Content>
          <Content component={ContentVariants.li}>
            <strong>
              Retained for one (1) year from job completion, then deleted:
            </strong>
            <br />
            The following data is retained for one (1) year after the job
            completion date and is then <strong>permanently deleted</strong>:
            <Content component={ContentVariants.ul}>
              <Content component={ContentVariants.li}>
                <strong>Job tasks data</strong> (including task names, status,
                and any task-related stored content) stored in the DCI database
              </Content>
              <Content component={ContentVariants.li}>
                <strong>Job task outputs</strong> (stdout/stderr) stored in
                Amazon S3
              </Content>
              <Content component={ContentVariants.li}>
                <strong>Job files data</strong> (including file names, size, and
                any file-related stored content) stored in the DCI database
              </Content>
              <Content component={ContentVariants.li}>
                <strong>Job files / artifacts</strong> (logs, JUnit reports, and
                other job-related files) stored in Amazon S3
              </Content>
              <Content component={ContentVariants.li}>
                <strong>Indexed analytics data</strong> stored in{" "}
                <strong>Elasticsearch</strong> (derived from the DCI database
                and/or job files)
              </Content>
            </Content>
          </Content>
        </Content>
        <Content component={ContentVariants.p}>
          After deletion, the affected job tasks, files, and
          Elasticsearch-indexed data are no longer accessible via the DCI UI or
          the DCI API, while the job metadata remains available.
        </Content>
      </PageSection>
    </NotAuthenticatedPage>
  );
}
